#
# BE playback pipeline: mixout-gain-dax-ctc-dai-copier.
#

<include/common/input_audio_format.conf>
<include/common/output_audio_format.conf>
<include/components/dai-copier.conf>
<include/components/gain.conf>
<include/components/mixout.conf>
<include/components/pipeline.conf>
<include/components/dolby-dax.conf>
<include/components/ctc.conf>

Class.Pipeline."mixout-gain-dax-ctc-dai-copier-playback" {

	<include/pipelines/pipeline-common.conf>

	attributes {
		!constructor [
			"index"
		]

		!immutable [
			"direction"
		]

		unique	"instance"
	}

	Object.Widget {
		mixout."1" {}
		dai-copier."1" {
			type dai_in
			num_input_audio_formats 1
			num_output_audio_formats 1
			num_input_pins 1

			Object.Base.input_audio_format [
				{
					in_bit_depth		32
					in_valid_bit_depth	32
				}
			]
			Object.Base.output_audio_format [
				{
					out_bit_depth		32
					out_valid_bit_depth	32
				}
			]
		}
		gain."1" {
			num_input_audio_formats 1
			num_output_audio_formats 1

			Object.Base.input_audio_format [
				{
					in_bit_depth		32
					in_valid_bit_depth	32
				}
			]
			Object.Base.output_audio_format [
				{
					out_bit_depth		32
					out_valid_bit_depth	32
				}
			]
		}
		dolby-dax."1" {
			num_input_audio_formats 1
			num_output_audio_formats 1
			Object.Base.input_audio_format [
				{
					in_rate			48000
					in_bit_depth		32
					in_valid_bit_depth	32
					ibs			"$[(256 * ($[($in_bit_depth / 8)])) * ($in_channels)]"
				}
			]
			Object.Base.output_audio_format [
				{
					out_rate		48000
					out_bit_depth		32
					out_valid_bit_depth	32
					obs			"$[(256 * ($[($out_bit_depth / 8)])) * ($out_channels)]"
				}
			]
		}
		ctc."1" {
			num_input_audio_formats 1
			num_output_audio_formats 1
			Object.Base.input_audio_format [
				{
					in_rate			48000
					in_bit_depth		32
					in_valid_bit_depth	32
					ibs			"$[(256 * ($[($in_bit_depth / 8)])) * ($in_channels)]"
				}
			]
			Object.Base.output_audio_format [
				{
					out_rate		48000
					out_bit_depth		32
					out_valid_bit_depth	32
					obs			"$[(256 * ($[($out_bit_depth / 8)])) * ($out_channels)]"
				}
			]
		}

		pipeline."1" {
			priority		0
			lp_mode		0
		}
	}

	Object.Base {
		!route [
			{
				source mixout.$index.1
				sink	gain.$index.1
			}
			{
				source gain.$index.1
				sink dolby-dax.$index.1
			}
			{
				source dolby-dax.$index.1
				sink ctc.$index.1
			}
		]
	}

	direction	"playback"
	dynamic_pipeline 1
	time_domain	"timer"
}
